### ISSUE TITLE
encode_address should not encode names

### ISSUE THREAD

**Issue by graup** [aergoio/herapy#65]
Currently it returns something like `dBRBrQyBCDR6VD5Uj3f7FtG` instead of `aergo.system`. Addresses with length < 12 or that are inside the list of system addresses should be encoded as plain text strings, not base58check.

**Comment by graup** [comment]
Also, the empty address is encoded as `8TAtRrz`.

**Comment by hanlsin** [comment]
I changed to support system contract addresses and name system. So it's included in release version 1.2.3.

But, what is the empty address for? Would you give me an example to understand?

**Comment by graup** [comment]
The empty address is used as the recipient for contract deployments.

**Comment by hanlsin** [comment]
Currently, there are 2 options to deploy a contract.

1. call `deploy_sc`
2. call `send_payload` without `to_address`, default is `None`, after making a deployment payload on your own.

So, in each case, `to_address` will be set as the empty address automatically.

**Comment by graup** [comment]
I'm talking about the result of get_tx, it contains the recipient address
in encoded form. For a deployment tx that will be the empty address.

**Comment by graup** [comment]
Ah, in the code it looks correct: https://github.com/aergoio/herapy/blob/88c4d728a4507fbe860ebf79499e2bee988a2a65/aergo/herapy/obj/transaction.py#L253

I'll check it again and add a failing test in case the issue still exists.

**Comment by graup** [comment]
I added a PR with a suggested code change and a test: https://github.com/aergoio/herapy/pull/67

**Comment by graup** [comment]
I'm not sure about the implementation, so I removed that and instead added another failing test ;)

**Comment by hanlsin** [comment]
I got what you need. It's for the `Address` class.

I fixed it in https://github.com/aergoio/herapy/commit/b34cd2cd672fb855efcb6d773607dee8dee287b5

I will release 1.2.5 with this.

**Comment by graup** [comment]
Thanks, nice and simple solution.

**Comment by graup** [comment]
@hanlsin here's another spot where the same fix needs to be applied: https://github.com/aergoio/herapy/blob/5a1c2487b1a67903382fcba422b59ded06a09ea2/aergo/herapy/obj/tx_result.py#L36

**Comment by hanlsin** [comment]
Oh...I missed it. Thanks.

**Comment by hanlsin** [comment]
It's included in v1.2.6.
