### ISSUE TITLE
Add support for GetNameInfo

### ISSUE THREAD

**Issue by graup** [aergoio/herapy#66]
Spec: https://docs.aergo.io/en/1.2/api/rpc-autogenerated.html#GetNameInfo

**Comment by hanlsin** [comment]
https://github.com/aergoio/herapy/commit/db588a079ac81cd86e8e0a05f43b2ba7c72bc01f

I committed to support 'GetNameInfo'. It will be included in release version 1.2.4.

**Comment by hanlsin** [comment]
It's gonna be more advanced after supporting with create/update name system.
